// ============================================================
// EchoLab: The Time Heart Registry — Game Data
// Original educational content. Fan-inspired framing only —
// not affiliated with BBC, Doctor Who, CCI, or Pearson VUE.
// ============================================================

export const DOMAINS = [
  { id: "A", name: "Preparing for the Procedure", short: "PREP",   weight: 5,  region: "medbay",  color: "#3BD6C6" },
  { id: "B", name: "Performing Echo Imaging",     short: "VIEWS",  weight: 24, region: "gallery", color: "#F5B84A" },
  { id: "C", name: "Valvular Findings",           short: "VALVES", weight: 25, region: null,      color: "#F4795B" },
  { id: "D", name: "Anatomy & Hemodynamics",      short: "HEMO",   weight: 29, region: null,      color: "#B48CF2" },
  { id: "E", name: "Physics of Ultrasound",       short: "PHYSICS",weight: 13, region: "engine",  color: "#7AB4FF" },
];

export const REGIONS = [
  {
    id: "medbay", domain: "A", name: "UNIT Medical Bay", weightLabel: "Domain A · 5% of exam",
    accent: "#3BD6C6", icon: "cross",
    tagline: "Where every scan begins — the patient in front of you.",
    doctorIntro: "Before you ever touch a probe, Lizzie, you protect the human being on the table. That's not the boring part. That's the whole point of the machine.",
    npc: { name: "Nurse Clara Vale", role: "Patient Care & Communication", init: "CV", color: "#3BD6C6",
      intro: "Welcome to the Med Bay, love. Rule one: the order, the identity, the story. Get those right and the images take care of themselves." },
    lessons: ["mb1", "mb2", "mb3"], game: null,
    unlock: { type: "start", label: "Open from Day 1" },
  },
  {
    id: "engine", domain: "E", name: "Physics Engine Room", weightLabel: "Domain E · 13% of exam",
    accent: "#7AB4FF", icon: "gear",
    tagline: "The hum beneath every image. Learn the engine, command the picture.",
    doctorIntro: "Everyone fears the physics. Don't. Physics is just the TARDIS engine of your machine — learn five levers and the whole console obeys you.",
    npc: { name: "Professor Gallifrey Gray", role: "Ultrasound Physics Instructor", init: "GG", color: "#7AB4FF",
      intro: "Ah, a new mind! Frequency, wavelength, attenuation — the grammar of sound. Speak it fluently and no artifact will ever lie to you again." },
    lessons: ["ph1", "ph2", "ph3", "ph4", "ph5"], game: "duel",
    unlock: { type: "lesson", lesson: "mb1", label: "Complete Med Bay Lesson 1" },
  },
  {
    id: "gallery", domain: "B", name: "Echo View Gallery", weightLabel: "Domain B · 24% of exam",
    accent: "#F5B84A", icon: "frame",
    tagline: "A museum of windows into the beating heart.",
    doctorIntro: "Every gallery has its masterpieces, Lizzie. Parasternal, apical, subcostal — each window is a fixed point. Stand in the right place and the heart shows you everything.",
    npc: { name: "Captain Doppler", role: "Views, Modes & Spectral Mentor", init: "CD", color: "#F5B84A",
      intro: "Captain Doppler, at your service! Windows first, waveforms second. Aim true, sample where the flow lives, and never fight the angle." },
    lessons: ["g1", "g2", "g3", "g4", "g5"], game: "mm",
    unlock: { type: "lesson", lesson: "ph1", label: "Complete Physics Lesson 1" },
  },
  {
    id: "citadel", domain: "C", name: "Valvular Citadel", weightLabel: "Domain C · 25% of exam",
    accent: "#F4795B", icon: "shield", tagline: "Stenosis, regurgitation, and the logic of severity.",
    doctorIntro: "", npc: { name: "Lady Valvula", role: "Valve Disease Mentor", init: "LV", color: "#F4795B", intro: "" },
    lessons: [], game: null,
    unlock: { type: "act", act: 3, label: "Act III — regenerates soon" },
  },
  {
    id: "observatory", domain: "D", name: "Hemodynamic Observatory", weightLabel: "Domain D · 29% of exam",
    accent: "#B48CF2", icon: "orbit", tagline: "Pressures, volumes, chambers — the physics of a living pump.",
    doctorIntro: "", npc: { name: "The Hemodynamic Oracle", role: "Formulas, Pressures & Flow", init: "HO", color: "#B48CF2", intro: "" },
    lessons: [], game: null,
    unlock: { type: "act", act: 3, label: "Act III — regenerates soon" },
  },
];

export const ROADMAP_ROOMS = [
  { name: "Doppler Rift",          act: "Act II",  note: "Spectral waveform deep-dives" },
  { name: "Stress Echo Arena",     act: "Act II",  note: "Exercise & pharmacologic protocols" },
  { name: "TEE Chamber",           act: "Act II",  note: "Probe planes & assisting" },
  { name: "Valvular Citadel",      act: "Act III", note: "Severity grading & prosthetics" },
  { name: "Hemodynamic Observatory", act: "Act III", note: "Pressures, chambers, function" },
  { name: "Pathology Archives",    act: "Act III", note: "Case files & masses" },
  { name: "Congenital Time Loop",  act: "Act III", note: "Shunts & congenital disease" },
  { name: "Mock Exam War Room",    act: "Act III", note: "Full timed registry simulations" },
];

// ============================ RANKS ============================
export const RANKS = [
  [1, "New Companion"], [5, "TARDIS Trainee"], [10, "Echo Apprentice"], [15, "View Navigator"],
  [20, "Doppler Adept"], [25, "Valve Specialist"], [30, "Hemodynamic Analyst"],
  [35, "Pathology Investigator"], [40, "Mock Exam Candidate"], [50, "Time Heart Registry Master"],
];

export const DOCTORS = [
  { n: 14, name: "The Fourteenth Doctor", act: "Act I", color: "#F5B84A", untilLevel: 12,
    tone: "Warm · encouraging · charismatic",
    quote: "Every echo image is a fixed point — if you know where to look." },
  { n: 13, name: "The Thirteenth Doctor", act: "Act II", color: "#3BD6C6", untilLevel: 25,
    tone: "Energetic · curious · science-forward",
    quote: "Right then, team — new window, new wonder. Let's investigate!" },
  { n: 12, name: "The Twelfth Doctor", act: "Act III", color: "#7AB4FF", untilLevel: 99,
    tone: "Brilliant · blunt · demanding · caring",
    quote: "Don't guess. Guessing is just being wrong with confidence. Explain it." },
];

// ============================ BADGES ============================
export const BADGES = [
  { id: "first_scan",   name: "First Scan",        how: "Answer your first question correctly", glyph: "◉", color: "#3BD6C6", mvp: true },
  { id: "bedside",      name: "Bedside Manner",    how: "Complete every Med Bay lesson", glyph: "✚", color: "#3BD6C6", mvp: true },
  { id: "physics_eng",  name: "Physics Engineer",  how: "Reach 80% mastery in the Engine Room", glyph: "⚙", color: "#7AB4FF", mvp: true },
  { id: "nyquist",      name: "Nyquist Tamer",     how: "Answer every aliasing question correctly", glyph: "∿", color: "#7AB4FF", mvp: true },
  { id: "parasternal",  name: "Parasternal Pro",   how: "Perfect battle in Gallery Lesson 1", glyph: "▣", color: "#F5B84A", mvp: true },
  { id: "apical",       name: "Apical Ace",        how: "Win Measure Match with a chain of 4+", glyph: "♦", color: "#F5B84A", mvp: true },
  { id: "duelist",      name: "Doppler Duelist",   how: "Win the Doppler Duel", glyph: "⚡", color: "#7AB4FF", mvp: true },
  { id: "dont_blink",   name: "Don't Blink",       how: "Defeat the Weeping Angels trial", glyph: "◈", color: "#EAF2FF", mvp: true },
  { id: "memory_keeper",name: "Memory Keeper",     how: "Clear 5 reviews from the Memory Core", glyph: "❖", color: "#B48CF2", mvp: true },
  { id: "streak3",      name: "Time Loop ×3",      how: "Reach a 3-day study streak", glyph: "↻", color: "#F5B84A", mvp: true },
  { id: "valve_guardian",name: "Valve Guardian",   how: "Act III — Valvular Citadel", glyph: "⛨", color: "#F4795B", mvp: false },
  { id: "aortic",       name: "Aortic Sentinel",   how: "Act III — aortic mastery", glyph: "▲", color: "#F4795B", mvp: false },
  { id: "mitral",       name: "Mitral Master",     how: "Act III — mitral mastery", glyph: "◄", color: "#F4795B", mvp: false },
  { id: "hemo_hero",    name: "Hemodynamic Hero",  how: "Act III — Observatory mastery", glyph: "◎", color: "#B48CF2", mvp: false },
  { id: "artifact_h",   name: "Artifact Hunter",   how: "Act II — Vashta Nerada hunt", glyph: "☍", color: "#7AB4FF", mvp: false },
  { id: "strain_seeker",name: "Strain Seeker",     how: "Act II — strain imaging", glyph: "≋", color: "#3BD6C6", mvp: false },
  { id: "stress_surv",  name: "Stress Echo Survivor", how: "Act II — Stress Arena", glyph: "♥", color: "#F4795B", mvp: false },
  { id: "tee_assist",   name: "TEE Assistant",     how: "Act II — TEE Chamber", glyph: "⌖", color: "#3BD6C6", mvp: false },
  { id: "mock_warrior", name: "Mock Exam Warrior", how: "Act III — War Room", glyph: "✦", color: "#B48CF2", mvp: false },
  { id: "registry_ready",name:"Registry Ready",    how: "Reach 90% overall readiness", glyph: "★", color: "#F5B84A", mvp: false },
];

export const ARTIFACTS = [
  { id: "sonic_case", name: "Sonic Screwdriver Casing", how: "Finish all Med Bay lessons", glyph: "⌇" },
  { id: "chrono",     name: "Chrono Fragment",          how: "Defeat the Weeping Angels", glyph: "◆" },
  { id: "primer",     name: "Gallifreyan Primer Page",  how: "Reach 60% mastery in 3 regions", glyph: "❂" },
];

// ============================ LINES ============================
export const LINES = {
  daily: [
    "The TARDIS charted your course today, Lizzie. Small steps, fixed points. Off we go.",
    "Twenty focused minutes bends the whole timeline. I've seen it. I've *caused* it.",
    "Weak topics aren't weaknesses — they're coordinates. We fly straight at them.",
    "You're not behind. You're exactly at the part of the story where the companion trains.",
    "Do the review set first. Future-you sent a message: she says thanks.",
    "Every question you miss today is one the exam can't surprise you with tomorrow.",
    "Streaks are little time loops. Keep this one spinning.",
  ],
  correct: [
    "Yes! See? Fixed point. You knew exactly where to look.",
    "Brilliant. Textbook — better than textbook, textbook's jealous.",
    "That's the one. The TARDIS just purred. She never purrs.",
    "Correct — and you knew *why*. That's the dangerous kind of clever.",
    "Molto bene! On to the next one.",
  ],
  wrong: [
    "Not that one — but look at the why. The why is the treasure.",
    "Wrong turn, right instincts. Read the explanation; it's a map.",
    "The Memory Core caught it. It'll circle back — that's how mastery works.",
    "Even Time Lords miss. Once. Read this and never again.",
  ],
  levelup: [
    "Level up! The TARDIS is showing off for you — ignore the sparks, that's affection.",
    "Look at you. New rank, same brilliant curiosity.",
    "Regeneration energy? No — that glow is just progress. Yours.",
  ],
};

// ============================ LESSONS ============================
// beats: k = kicker label; challenge beat has q {stem, ch, ans, why}
export const LESSONS = {
  mb1: {
    id: "mb1", region: "medbay", title: "Before the Probe Touches Skin", sub: "Orders · identity · history",
    beats: [
      { k: "CONCEPT", t: "Verify, then scan", b: "Every study starts with three checks: a valid order that matches the clinical question, the right patient confirmed with two identifiers (full name + date of birth), and the story — symptoms, history, prior studies. If the order and the patient's story disagree, you stop and verify with the referring provider." },
      { k: "WHY IT MATTERS", t: "Wrong-exam events are never-events", b: "Scanning the wrong patient or the wrong indication wastes the one thing echo can't image: time. Prior studies matter too — knowing yesterday's EF or effusion size turns your scan into a comparison instead of a guess." },
      { k: "MEMORY HOOK", t: "O.I.S. — Order, Identity, Story", b: "The TARDIS won't dematerialize without coordinates. You don't scan without O.I.S.: the Order is valid, the Identity is confirmed twice, the Story fits the order." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Which pair counts as two acceptable patient identifiers?", ch: ["Full name + room number", "Full name + date of birth", "First name + diagnosis"], ans: 1, why: "Room numbers and diagnoses can change or be shared — name plus DOB uniquely identifies the patient." } },
    ],
    battle: ["a1", "a2", "a3", "a11"],
  },
  mb2: {
    id: "mb2", region: "medbay", title: "Position, Protect, Preserve", sub: "Positioning · ergonomics · infection control",
    beats: [
      { k: "CONCEPT", t: "Position the heart toward you", b: "Left lateral decubitus swings the heart against the chest wall and pushes lung out of the way — that's why parasternal and apical windows love it. Subcostal wants supine with bent knees; suprasternal wants the neck extended over a shoulder roll." },
      { k: "WHY IT MATTERS", t: "Your career is an instrument too", b: "Work-related musculoskeletal injury ends sonography careers. Keep arm abduction under about 30°, bring the patient to you, adjust bed and chair height, and support your scanning arm. Between patients: hand hygiene and low-level disinfection of the transducer — TTE on intact skin is a noncritical device." },
      { k: "MEMORY HOOK", t: "Tilt the patient, not your spine", b: "The TARDIS rotates around its pilot. Rotate the patient and the bed around you — never fold yourself around the machine." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Best position for parasternal and apical windows?", ch: ["Supine, arms overhead", "Left lateral decubitus", "Right lateral decubitus"], ans: 1, why: "Left lateral decubitus brings the heart forward against the chest wall and displaces lung tissue." } },
    ],
    battle: ["a4", "a5", "a6", "a7", "a12"],
  },
  mb3: {
    id: "mb3", region: "medbay", title: "Words, Reports & Red Flags", sub: "Communication · reports · critical findings",
    beats: [
      { k: "CONCEPT", t: "Explain the journey, not the destination", b: "Tell patients what will happen — gel, probe pressure, position changes, roughly how long — in plain language. What you never do is interpret: 'the cardiologist will read this and your provider will discuss results' is the professional answer to 'is my heart okay?'" },
      { k: "WHY IT MATTERS", t: "Some findings can't wait for the report", b: "A large effusion with collapsing chambers, a mobile LV thrombus, a dissection flap — critical findings get communicated to the interpreting physician immediately, per lab protocol, and documented. Your worksheet carries measurements, views, rhythm, and technical limitations; the physician makes the final interpretation." },
      { k: "MEMORY HOOK", t: "Sonographers describe, physicians diagnose", b: "You're the scanner, not the oracle. Describe what you see to the right person at the right speed — instantly if it's dangerous." },
      { k: "TRY IT", t: "Quick check", q: { stem: "You see a large new pericardial effusion with RV collapse. Best action?", ch: ["Note it in the worksheet for tomorrow's read", "Tell the patient it looks serious", "Notify the interpreting physician before the patient leaves"], ans: 2, why: "Possible tamponade is a critical finding — escalate immediately per protocol; never interpret to the patient." } },
    ],
    battle: ["a8", "a9", "a10"],
  },
  ph1: {
    id: "ph1", region: "engine", title: "Waves & the Speed Limit", sub: "Frequency · wavelength · propagation",
    beats: [
      { k: "CONCEPT", t: "Sound is a mechanical wave", b: "Ultrasound is pressure waves above 20 kHz. Frequency is set by the transducer; propagation speed is set by the medium — soft tissue averages 1,540 m/s no matter what probe you hold. Wavelength = speed ÷ frequency, so higher frequency means shorter wavelength." },
      { k: "WHY IT MATTERS", t: "The great trade-off", b: "Higher frequency → shorter wavelength → crisper detail (better axial resolution) but faster attenuation → less depth. That's why pediatric probes run high and difficult adult chests run low. Every knob decision descends from this one trade." },
      { k: "MEMORY HOOK", t: "1540 — the TARDIS speed limit", b: "Sound in soft tissue always cruises at 1,540 m/s. The machine assumes it; artifacts happen when reality disobeys. Carve '1540' into your hearts. Both of them." },
      { k: "TRY IT", t: "Quick check", q: { stem: "You switch from a 2.5 MHz to a 5 MHz transducer. What happens?", ch: ["Better detail, less penetration", "Better detail, more penetration", "Propagation speed doubles"], ans: 0, why: "Frequency up → axial resolution improves but attenuation rises, costing depth. Speed belongs to the tissue, not the probe." } },
    ],
    battle: ["e1", "e2", "e3"],
  },
  ph2: {
    id: "ph2", region: "engine", title: "Losing the Signal", sub: "Attenuation · reflection · refraction",
    beats: [
      { k: "CONCEPT", t: "Three thieves of sound", b: "As the beam travels it weakens — attenuation. Absorption (sound → heat) steals the most; reflection bounces energy back at impedance boundaries; scattering sprays it from small structures. Attenuation grows with frequency and with depth." },
      { k: "WHY IT MATTERS", t: "Boundaries make the image", b: "Echoes are born where acoustic impedance changes. Perpendicular incidence sends specular echoes straight home — that's why you rock the probe until a valve 'lights up.' Oblique incidence plus different propagation speeds bends the transmitted beam (refraction) and can draw structures in the wrong place." },
      { k: "MEMORY HOOK", t: "A.R.S. — Absorb, Reflect, Scatter", b: "The signal's three tax collectors. Absorption always takes the biggest cut." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Refraction requires oblique incidence plus…", ch: ["Identical propagation speeds", "Different propagation speeds", "A strong reflector"], ans: 1, why: "Snell's law: the beam bends only when it crosses obliquely into a medium with a different speed." } },
    ],
    battle: ["e4", "e5", "e6"],
  },
  ph3: {
    id: "ph3", region: "engine", title: "Sharp & Fast", sub: "Resolution · frame rate · knobs",
    beats: [
      { k: "CONCEPT", t: "Three resolutions to rule them all", b: "Axial: separating things along the beam — equals spatial pulse length ÷ 2, so shorter pulses (higher frequency, more damping) win. Lateral: separating things side-by-side — equals beam width, best at the focus. Temporal: how truly you capture motion — that's frame rate." },
      { k: "WHY IT MATTERS", t: "The heart moves; your image must keep up", b: "Shallower depth, narrower sector, fewer focal zones → faster frames. Receiver gain brightens echoes you already have; TGC balances brightness across depth; output power raises patient exposure — ALARA says reach for gain first. Dynamic range down = punchier contrast, fewer grays." },
      { k: "MEMORY HOOK", t: "Axial = Along. Lateral = beam waist.", b: "Axial and Along both start with A. Lateral is best where the beam is skinniest — at the focus, like a corseted waist." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Fastest way to raise frame rate on a deep, wide sector?", ch: ["Increase depth", "Narrow the sector width", "Add focal zones"], ans: 1, why: "Fewer scan lines per frame → faster frames. Depth and extra foci slow you down." } },
    ],
    battle: ["e7", "e8", "e9", "e10", "e11", "e12"],
  },
  ph4: {
    id: "ph4", region: "engine", title: "Ghosts in the Machine", sub: "Shadowing · reverberation · mirrors · lobes",
    beats: [
      { k: "CONCEPT", t: "Artifacts are lies with rules", b: "Shadowing: a strong attenuator (calcium, rib) blocks the beam — darkness beyond. Reverberation: two strong parallel reflectors ping-pong the sound — equally spaced repeating lines (comet tails are the compact version). Mirror image: a strong reflector like pericardium paints a duplicate deeper than reality. Side/grating lobes: off-axis energy sketches faint false echoes inside cavities." },
      { k: "WHY IT MATTERS", t: "Every artifact accuses the machine, not the heart", b: "A 'mass' that crosses anatomic boundaries, repeats at even intervals, or vanishes in a second window is an artifact confessing. Change the window, angle, frequency, or harmonics before you ever change the diagnosis." },
      { k: "MEMORY HOOK", t: "Ghosts can't survive a second window", b: "Real pathology persists from every view. Ghosts evaporate when you walk around them." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Equally spaced bright lines repeating deeper and deeper are…", ch: ["Reverberation", "Shadowing", "Refraction"], ans: 0, why: "The beam bounces between parallel reflectors; each round trip paints another line at equal spacing." } },
    ],
    battle: ["e13", "e14", "e15", "e16"],
  },
  ph5: {
    id: "ph5", region: "engine", title: "The Nyquist Wall", sub: "Aliasing · PRF · PW vs CW",
    beats: [
      { k: "CONCEPT", t: "Sampling has a speed limit", b: "Pulsed-wave Doppler samples flow at the PRF. It can only measure Doppler shifts up to PRF ÷ 2 — the Nyquist limit. Faster flow wraps around the baseline: aliasing. Continuous-wave never aliases (always transmitting and receiving) but can't tell you *where* along the beam the velocity lives — range ambiguity." },
      { k: "WHY IT MATTERS", t: "Choosing PW vs CW is a clinical decision", b: "Locating flow at a spot (LVOT VTI)? PW. Measuring a jet over 2 m/s (aortic stenosis)? CW. If PW aliases: shift the baseline, raise the velocity scale (PRF), lower transmit frequency, use a shallower gate — or surrender to CW." },
      { k: "MEMORY HOOK", t: "PW knows WHERE. CW knows HOW FAST.", b: "Pulsed = Position. Continuous = Celerity. You can know where or how fast — never both perfectly. Very Time-Lord, velocity." },
      { k: "TRY IT", t: "Quick check", q: { stem: "A PW trace wraps around the baseline. First knob to try?", ch: ["Increase 2D gain", "Shift the baseline / raise the scale", "Add a focal zone"], ans: 1, why: "Baseline shift and higher PRF reallocate the Nyquist range — the standard first fixes for aliasing." } },
    ],
    battle: ["e17", "e18", "e19"],
  },
  g1: {
    id: "g1", region: "gallery", title: "The Parasternal Windows", sub: "PLAX · PSAX levels",
    beats: [
      { k: "CONCEPT", t: "PLAX — the establishing shot", b: "Probe at the left sternal border, 3rd–4th intercostal space, marker toward the right shoulder (~10 o'clock). You see LA, LV, mitral and aortic valves, LVOT, and the RVOT riding anteriorly. Notice who's missing: the right atrium." },
      { k: "WHY IT MATTERS", t: "Rotate 90° and descend the levels", b: "Marker to the left shoulder gives PSAX. Sweep from the aortic-valve level (tri-leaflet 'Mercedes' AV hugged by RA, TV, RV, PA) down through mitral 'fish mouth' to the papillary-muscle level — the classic slice for regional wall motion." },
      { k: "MEMORY HOOK", t: "10 o'clock to 2 o'clock", b: "PLAX points the marker at 10 (right shoulder); rotate clockwise to ~2 (left shoulder) and the long axis becomes the short. One wrist turn, one whole new museum wing." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Which chamber is NOT seen in a standard PLAX?", ch: ["Left atrium", "Right atrium", "Left ventricle"], ans: 1, why: "PLAX shows LA, LV, RVOT, MV, AV — the RA needs RV inflow, PSAX-AV, or apical views." } },
    ],
    battle: ["b1", "b2", "b3", "b4"],
  },
  g2: {
    id: "g2", region: "gallery", title: "The Apical Family", sub: "A4C · A5C · A2C · A3C",
    beats: [
      { k: "CONCEPT", t: "Four siblings from one window", b: "From the apical impulse, marker toward the patient's left (~3 o'clock): A4C shows all four chambers. Tilt anteriorly and the LVOT/AV appears — A5C. Rotate counterclockwise ~60° for A2C (anterior + inferior walls), and on to ~120° for A3C, the apical long axis (anteroseptum + inferolateral wall + LVOT)." },
      { k: "WHY IT MATTERS", t: "Doppler lives here", b: "Apical windows align the beam with flow: mitral inflow and annular tissue Doppler in A4C, LVOT and aortic jets in A5C/A3C. Guard against foreshortening — a falsely short, round LV lies about volumes and wall motion." },
      { k: "MEMORY HOOK", t: "4 → 5 is a tilt. 4 → 2 → 3 is a turn.", b: "Tilt up to add the fifth chamber; rotate to walk 4-2-3 like a companion counting doors down a TARDIS corridor." },
      { k: "TRY IT", t: "Quick check", q: { stem: "From A4C you tilt the probe anteriorly. You are now in…", ch: ["A2C", "A5C", "Subcostal 4C"], ans: 1, why: "Anterior tilt opens the LVOT and aortic valve — the 'fifth chamber.'" } },
    ],
    battle: ["b5", "b6", "b7", "b8"],
  },
  g3: {
    id: "g3", region: "gallery", title: "Under & Above", sub: "Subcostal · IVC · suprasternal",
    beats: [
      { k: "CONCEPT", t: "The window under the ribs", b: "Subcostal views come from below the xiphoid, patient supine with knees bent. The beam meets the interatrial septum head-on — best view to hunt ASDs — and it's the rescue window in COPD and hyperinflated chests, and a superb effusion spotter." },
      { k: "WHY IT MATTERS", t: "The IVC is a pressure gauge", b: "Rotate to the long-axis IVC: diameter ≤ 2.1 cm collapsing > 50% with a sniff ≈ RA pressure 3 mmHg; dilated and barely collapsing ≈ 15 mmHg. Above the chest, the suprasternal notch (neck extended) shows the aortic arch — coarctation, dissection flaps, arch flow." },
      { k: "MEMORY HOOK", t: "Skinny and shy = 3. Big and bold = 15.", b: "A small IVC that hides when the patient sniffs means low RA pressure; a wide one that won't budge means high." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Best window to evaluate the interatrial septum for an ASD?", ch: ["PLAX", "Subcostal 4-chamber", "Suprasternal notch"], ans: 1, why: "Subcostal puts the beam perpendicular to the septum, avoiding false dropout seen apically." } },
    ],
    battle: ["b9", "b10", "b11"],
  },
  g4: {
    id: "g4", region: "gallery", title: "Modes & Maps", sub: "M-mode · color · PW/CW · tissue Doppler",
    beats: [
      { k: "CONCEPT", t: "One heart, four instruments", b: "M-mode fires one scan line thousands of times a second — unbeatable temporal resolution for timing motion. Color Doppler is pulsed-wave in a box: it maps flow direction but inherits aliasing. PW measures velocity at a chosen spot; CW captures the fastest velocity anywhere along the line. Tissue Doppler flips the filters — high-amplitude, LOW-velocity myocardium (e′ at the mitral annulus)." },
      { k: "WHY IT MATTERS", t: "Pick the instrument for the question", b: "Timing subtle valve motion? M-mode. Where is the jet? Color. Velocity at the LVOT for stroke volume? PW. Peak aortic-stenosis jet at 4 m/s? CW — PW would alias hopelessly. Diastolic function? Tissue Doppler e′." },
      { k: "MEMORY HOOK", t: "Color is just PW wearing a mosaic coat", b: "If color speckles into mosaic at normal velocities, check its scale — same Nyquist physics, prettier disguise." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Best modality for a 4.2 m/s aortic stenosis jet?", ch: ["PW Doppler", "CW Doppler", "Tissue Doppler"], ans: 1, why: "CW has no Nyquist ceiling — high jets need it. PW would alias far below 4.2 m/s." } },
    ],
    battle: ["b12", "b13", "b14", "b15"],
  },
  g5: {
    id: "g5", region: "gallery", title: "Bubbles & Stress", sub: "Saline · LV contrast · stress echo",
    beats: [
      { k: "CONCEPT", t: "Two kinds of bubbles", b: "Agitated saline bubbles are too big to cross the lungs — they light up the RIGHT heart. Bubbles appearing in the left heart within ~3–6 beats mean an intracardiac shunt (PFO/ASD); a late arrival suggests pulmonary AVM. Transpulmonary contrast agents DO cross the lungs and opacify the LV — used when 2+ contiguous segments are unreadable or to hunt apical thrombus." },
      { k: "WHY IT MATTERS", t: "Stress is a race against recovery", b: "Exercise stress echo compares wall motion at rest and peak — acquire post-exercise images within about 60–90 seconds, before heart rate falls. Pharmacologic (dobutamine) builds in stages; a segment that improves at low dose then fails at peak — the biphasic response — is viable but ischemic. Atropine helps reach target heart rate." },
      { k: "MEMORY HOOK", t: "Saline = Shunts. Contrast = Chambers.", b: "S goes with S, C goes with C. And after the treadmill: sprint, don't stroll, to the probe." },
      { k: "TRY IT", t: "Quick check", q: { stem: "Saline bubbles appear in the LA three beats after RA opacification. This suggests…", ch: ["Normal study", "Intracardiac shunt (e.g., PFO)", "Pulmonary AVM"], ans: 1, why: "Early left-heart bubbles (≤3–6 beats) cross at atrial level; late arrival points to a pulmonary route." } },
    ],
    battle: ["b16", "b17", "b18", "b19"],
  },
};

// ============================ QUESTIONS ============================
// diff: 1 easy · 2 medium · 3 hard. ans = index. ww aligned to choices ("" at correct).
export const QUESTIONS = {
  // ---------- DOMAIN A — Med Bay (12) ----------
  a1: { d: "A", topic: "Verifying orders", diff: 1,
    stem: "The order reads “TTE — evaluate murmur,” but the patient says she was scheduled for a leg ultrasound. Best next step?",
    ch: ["Proceed — the written order takes priority", "Verify the order and indication with the referring provider", "Perform both studies to be thorough", "Let the patient choose which exam to do"],
    ans: 1,
    exp: "Any mismatch between the order and the patient's understanding must be resolved before scanning. Verifying protects the patient, the diagnosis, and the lab.",
    ww: ["Scanning through a known discrepancy risks a wrong-exam event.", "", "Performing an unordered study is outside scope and improper.", "Patients don't select orders — providers do."],
    pearl: "Order · Identity · Story — if any of the three disagree, stop and verify." },
  a2: { d: "A", topic: "Patient identification", diff: 1,
    stem: "Which pair is acceptable for confirming patient identity before an echo?",
    ch: ["Full name and room number", "Full name and date of birth", "First name and diagnosis", "Medical record number alone"],
    ans: 1,
    exp: "Two independent identifiers tied to the person — typically full name plus DOB — are required. Room numbers and diagnoses can change or be shared.",
    ww: ["Room numbers change and are not tied to the person.", "", "A diagnosis is neither unique nor confirmed.", "A single identifier is never sufficient."],
    pearl: "" },
  a3: { d: "A", topic: "Prior studies", diff: 1,
    stem: "The most important reason to review a patient's prior echo before scanning is to…",
    ch: ["Bill the study correctly", "Copy the previous measurements", "Compare interval change and anticipate difficult windows", "Skip views that were normal before"],
    ans: 2,
    exp: "Priors turn a snapshot into a trend — EF change, effusion growth, valve progression — and warn you about tough windows or variants.",
    ww: ["Billing isn't the clinical purpose of review.", "Measurements must be made fresh, never copied.", "", "A complete protocol is still required every time."],
    pearl: "Interval change is often the entire clinical question." },
  a4: { d: "A", topic: "Positioning", diff: 1,
    stem: "Why is the left lateral decubitus position preferred for most transthoracic imaging?",
    ch: ["It lowers the heart rate", "It brings the heart against the chest wall and displaces lung", "It makes the patient more comfortable than supine", "It increases venous return"],
    ans: 1,
    exp: "Gravity swings the heart anteriorly against the ribs and shifts lung away, widening the parasternal and apical windows.",
    ww: ["Position doesn't meaningfully treat heart rate.", "", "Comfort varies; that isn't the imaging rationale.", "It doesn't raise venous return — that's a leg-raise effect."],
    pearl: "" },
  a5: { d: "A", topic: "Ergonomics", diff: 2,
    stem: "Which habit most reduces a sonographer's risk of work-related musculoskeletal injury?",
    ch: ["Leaning across the bed to reach the apex", "Keeping scanning-arm abduction under ~30° and adjusting bed height", "Scanning with a straightened, locked elbow", "Holding your breath during sweeps for stability"],
    ans: 1,
    exp: "Neutral posture is the core rule: arm close to the body (<30° abduction), bed and chair adjusted, patient brought toward you.",
    ww: ["Reaching across the bed is the classic injury pattern.", "", "A locked elbow transmits strain to the shoulder.", "Breath-holding steadies nothing and fatigues you."],
    pearl: "Move the patient and the furniture — not your shoulder." },
  a6: { d: "A", topic: "Infection control", diff: 1,
    stem: "After a routine TTE on intact skin, the transducer should be…",
    ch: ["Sterilized with high-level disinfectant", "Cleaned and low-level disinfected per facility policy", "Rinsed with water only", "Wiped only if visibly soiled"],
    ans: 1,
    exp: "A TTE probe on intact skin is a noncritical device: remove gel, then low-level disinfect between every patient.",
    ww: ["High-level disinfection is for semicritical devices like TEE probes.", "", "Water alone doesn't disinfect.", "Disinfection is required after every patient, soiled or not."],
    pearl: "TEE probe = semicritical = high-level disinfection. TTE = noncritical = low-level." },
  a7: { d: "A", topic: "Standard precautions", diff: 1,
    stem: "Standard precautions require hand hygiene…",
    ch: ["Only after patients with known infections", "Before and after every patient contact", "Only when gloves were not worn", "Once at the start of each shift"],
    ans: 1,
    exp: "Hand hygiene brackets every patient encounter, regardless of diagnosis, and gloves never replace it.",
    ww: ["Precautions are universal — infection status is often unknown.", "", "Gloves supplement, never substitute.", "Once per shift is nowhere near sufficient."],
    pearl: "" },
  a8: { d: "A", topic: "Explaining the procedure", diff: 1,
    stem: "The best way to explain an echo to an anxious patient is to…",
    ch: ["Use precise medical terminology to build trust", "Describe the steps in plain language and what they'll feel", "Reassure them the results will be normal", "Say as little as possible to save time",],
    ans: 1,
    exp: "Plain-language expectations — gel, probe pressure, position changes, duration — lower anxiety and improve cooperation and image quality.",
    ww: ["Jargon increases anxiety and confusion.", "", "Never promise results — you can't know and mustn't interpret.", "Silence breeds fear and worse windows."],
    pearl: "A calm patient is a better acoustic window." },
  a9: { d: "A", topic: "Critical findings", diff: 2,
    stem: "During a routine outpatient echo you find a large mobile mass in the LV apex. Best action?",
    ch: ["Finish and submit the study for routine reading", "Notify the interpreting physician promptly per lab protocol before the patient leaves", "Tell the patient they have a clot and must go to the ER", "Repeat the study tomorrow to confirm"],
    ans: 1,
    exp: "A probable mobile thrombus is a critical finding: complete needed images, escalate immediately through the lab's protocol, and document the communication.",
    ww: ["Routine turnaround risks an embolic event in the interim.", "", "Diagnosing to the patient exceeds sonographer scope.", "Delay for a repeat adds risk without benefit."],
    pearl: "Critical findings travel at CW speed — immediately, along the correct line." },
  a10: { d: "A", topic: "Scope of practice", diff: 1,
    stem: "A patient asks mid-scan, “Is my heart failing?” The sonographer should…",
    ch: ["Give an honest summary of the findings", "Explain that the cardiologist will interpret and their provider will discuss results", "Say everything looks fine to keep them calm", "Show them the EF measurement on screen"],
    ans: 1,
    exp: "Interpretation and diagnosis belong to the physician. Redirect warmly and professionally without dismissing the concern.",
    ww: ["Interpreting findings is outside sonographer scope.", "", "False reassurance is interpretation too — and may be wrong.", "Showing numbers invites interpretation you can't provide."],
    pearl: "" },
  a11: { d: "A", topic: "Report preparation", diff: 2,
    stem: "Which belongs on the sonographer's preliminary worksheet?",
    ch: ["Final diagnosis and treatment plan", "Measurements, views obtained, rhythm, and technical limitations", "Only abnormal findings", "The sonographer's interpretation summary"],
    ans: 1,
    exp: "The worksheet documents what was acquired and measured — including limitations like poor windows — so the physician can render the final interpretation.",
    ww: ["Diagnosis and treatment are the physician's domain.", "", "Normal findings and completeness matter for comparison.", "Sonographers describe; the interpretation is the reader's."],
    pearl: "" },
  a12: { d: "A", topic: "Positioning — SSN", diff: 2,
    stem: "Proper positioning for the suprasternal notch window includes…",
    ch: ["Left lateral decubitus with arm raised", "Supine with the neck extended over a shoulder roll", "Sitting upright leaning forward", "Prone with head turned left"],
    ans: 1,
    exp: "Extending the neck (shoulder roll, chin up, head turned slightly) opens the notch so the beam reaches the aortic arch.",
    ww: ["That's the setup for parasternal/apical windows.", "", "Upright leaning forward suits posterior effusion tapping, not SSN.", "Prone blocks the notch entirely."],
    pearl: "" },

  // ---------- DOMAIN E — Physics Engine Room (19) ----------
  e1: { d: "E", topic: "Frequency & resolution", diff: 1,
    stem: "Increasing transducer frequency has which paired effect?",
    ch: ["Better axial resolution · less penetration", "Better axial resolution · more penetration", "Worse axial resolution · more penetration", "No change in resolution · less penetration"],
    ans: 0,
    exp: "Higher frequency shortens the pulse (better axial detail) but attenuates faster, sacrificing depth.",
    ww: ["", "Penetration falls as frequency rises — attenuation is frequency-dependent.", "Axial resolution improves, not worsens.", "Resolution clearly changes with frequency."],
    pearl: "Detail and depth sit on opposite ends of the frequency see-saw." },
  e2: { d: "E", topic: "Propagation speed", diff: 1,
    stem: "The propagation speed of ultrasound in soft tissue is determined by…",
    ch: ["The transducer frequency", "The properties of the medium (stiffness and density)", "The output power setting", "The pulse repetition frequency"],
    ans: 1,
    exp: "Speed belongs to the medium — about 1,540 m/s in average soft tissue — and no probe or knob changes it.",
    ww: ["Changing frequency changes wavelength, not speed.", "", "Power changes amplitude, not speed.", "PRF changes sampling, not propagation."],
    pearl: "1,540 m/s — the machine's built-in assumption for all its distance math." },
  e3: { d: "E", topic: "Wavelength", diff: 2,
    stem: "For a 5 MHz beam in soft tissue, the approximate wavelength is…",
    ch: ["0.31 mm", "3.1 mm", "0.031 mm", "1.54 mm"],
    ans: 0,
    exp: "λ = c ÷ f = 1.54 mm/µs ÷ 5 MHz ≈ 0.31 mm. Higher frequency, shorter wavelength.",
    ww: ["", "Off by 10× — that would be a 0.5 MHz beam.", "Off by 10× the other way.", "1.54 mm is the wavelength at 1 MHz."],
    pearl: "Quick trick: λ(mm) ≈ 1.54 ÷ f(MHz)." },
  e4: { d: "E", topic: "Attenuation", diff: 1,
    stem: "The greatest contributor to attenuation in soft tissue is…",
    ch: ["Reflection", "Scattering", "Absorption", "Refraction"],
    ans: 2,
    exp: "Absorption converts sound to heat and dominates soft-tissue attenuation, which grows with frequency and depth.",
    ww: ["Reflection returns useful signal but isn't the main loss.", "Scattering is a minor contributor from small structures.", "", "Refraction redirects the beam; it isn't the main energy loss."],
    pearl: "" },
  e5: { d: "E", topic: "Reflection", diff: 2,
    stem: "A strong specular echo returns to the transducer when the beam strikes a smooth boundary…",
    ch: ["At any angle, if gain is high", "Perpendicular to the interface", "Parallel to the interface", "Only if the media have identical impedance"],
    ans: 1,
    exp: "Specular reflectors behave like mirrors: perpendicular incidence sends the echo straight back. Impedance MISMATCH creates the echo in the first place.",
    ww: ["Gain amplifies received echoes; it can't redirect them.", "", "Parallel incidence returns almost nothing.", "Identical impedance produces no reflection at all."],
    pearl: "That's why you rock and angle until the valve 'flashes' — you found perpendicular." },
  e6: { d: "E", topic: "Refraction", diff: 2,
    stem: "Refraction artifact — a structure drawn in the wrong lateral position — requires…",
    ch: ["Oblique incidence and different propagation speeds", "Perpendicular incidence and equal speeds", "A strong attenuator in the near field", "High pulse repetition frequency"],
    ans: 0,
    exp: "Snell's law: crossing a boundary obliquely between media of different speeds bends the transmitted beam, misplacing structures sideways.",
    ww: ["", "Perpendicular incidence with equal speeds produces no bending.", "Attenuators cause shadowing, not lateral displacement.", "PRF governs aliasing, not beam bending."],
    pearl: "" },
  e7: { d: "E", topic: "Axial resolution", diff: 2,
    stem: "Axial resolution improves with…",
    ch: ["Longer spatial pulse length", "Higher frequency and more damping (shorter pulses)", "Wider beam width", "Higher receiver gain"],
    ans: 1,
    exp: "Axial resolution = SPL ÷ 2. Shorter pulses — higher frequency, heavier damping — separate structures along the beam.",
    ww: ["Longer pulses blur structures together axially.", "", "Beam width is lateral resolution's territory.", "Gain brightens; it never sharpens."],
    pearl: "Axial = Along the beam. Both start with A." },
  e8: { d: "E", topic: "Lateral resolution", diff: 2,
    stem: "Lateral resolution is best…",
    ch: ["In the far field", "At the focal zone, where the beam is narrowest", "Immediately at the transducer face", "At the deepest part of the image"],
    ans: 1,
    exp: "Lateral resolution equals beam width, and the beam is narrowest at its focus — place the focal zone at your structure of interest.",
    ww: ["The far field diverges and widens.", "", "The near field is wider than the focal waist.", "Depth widens the beam and worsens it."],
    pearl: "" },
  e9: { d: "E", topic: "Temporal resolution", diff: 1,
    stem: "Temporal resolution refers to…",
    ch: ["The smallest detail visible along the beam", "How accurately motion is captured over time (frame rate)", "The number of gray shades displayed", "The beam's ability to separate side-by-side structures"],
    ans: 1,
    exp: "Temporal resolution is the frame rate — critical for a structure that moves 60–100 times a minute.",
    ww: ["That's axial resolution.", "", "That's dynamic range.", "That's lateral resolution."],
    pearl: "M-mode, sampling one line thousands of times per second, is the temporal-resolution champion." },
  e10: { d: "E", topic: "Frame rate", diff: 1,
    stem: "Which adjustment increases frame rate?",
    ch: ["Increasing imaging depth", "Decreasing imaging depth", "Widening the sector", "Adding multiple focal zones"],
    ans: 1,
    exp: "Shallower depth shortens each pulse's round trip, so more frames fit per second. Narrowing the sector helps the same way.",
    ww: ["Deeper listening time slows frames.", "", "More lines per frame = slower frames.", "Each focal zone multiplies pulses per line."],
    pearl: "" },
  e11: { d: "E", topic: "Gain vs output power", diff: 1,
    stem: "The image is too dark. Following ALARA, the first adjustment should be…",
    ch: ["Increase output power", "Increase receiver gain / adjust TGC", "Switch to a higher frequency", "Increase dynamic range"],
    ans: 1,
    exp: "Receiver gain amplifies echoes already received — no added patient exposure. Reach for it (and TGC) before output power.",
    ww: ["Power raises exposure; it's the later resort under ALARA.", "", "Higher frequency worsens penetration — often darker still.", "Dynamic range alters contrast, not overall brightness."],
    pearl: "ALARA: As Low As Reasonably Achievable — gain first, power last." },
  e12: { d: "E", topic: "Dynamic range", diff: 2,
    stem: "Decreasing dynamic range (compression) makes the image…",
    ch: ["Higher contrast with fewer shades of gray", "Softer with more shades of gray", "Brighter overall", "Deeper in penetration"],
    ans: 0,
    exp: "Narrowing the displayed range squeezes echoes into fewer gray levels — a punchier, higher-contrast image.",
    ww: ["", "That describes INCREASING dynamic range.", "Overall brightness is gain's job.", "Penetration is unchanged by display compression."],
    pearl: "" },
  e13: { d: "E", topic: "Shadowing", diff: 1,
    stem: "A heavily calcified aortic valve causes an anechoic band beyond it. This artifact is…",
    ch: ["Acoustic shadowing", "Reverberation", "Mirror image", "Side lobe artifact"],
    ans: 0,
    exp: "Strong attenuators block the beam; everything distal is starved of sound — a shadow that can hide pathology behind it.",
    ww: ["", "Reverberation adds repeating lines, not absence.", "Mirror image duplicates a structure deeper.", "Side lobes paint faint false echoes, not darkness."],
    pearl: "Shadowing is also a clue — it screams 'calcium (or prosthesis) here.'" },
  e14: { d: "E", topic: "Reverberation", diff: 2,
    stem: "Multiple bright, equally spaced parallel lines marching deeper into the image indicate…",
    ch: ["Refraction", "Reverberation between two strong parallel reflectors", "Acoustic enhancement", "Aliasing"],
    ans: 1,
    exp: "Sound ping-pongs between parallel reflectors; each extra round trip paints another line at equal spacing. Comet-tail is its compact cousin.",
    ww: ["Refraction displaces laterally, without repetition.", "", "Enhancement brightens beyond weak attenuators.", "Aliasing is a Doppler wraparound, not a 2D line pattern."],
    pearl: "" },
  e15: { d: "E", topic: "Mirror image", diff: 2,
    stem: "A duplicate of the heart appears deeper than the pericardium. The responsible artifact is…",
    ch: ["Mirror image from a strong specular reflector", "Grating lobes", "Shadowing", "Range ambiguity"],
    ans: 0,
    exp: "The pericardium acts as an acoustic mirror: redirected echoes take longer to return, so the machine paints a copy deeper than reality.",
    ww: ["", "Grating lobes misplace structures laterally.", "Shadowing removes signal; it doesn't duplicate.", "Range ambiguity is a high-PRF Doppler issue."],
    pearl: "" },
  e16: { d: "E", topic: "Side lobes", diff: 2,
    stem: "Faint echoes appear inside the aortic lumen but vanish from another window. Likely cause?",
    ch: ["A true intraluminal mass", "Side- or grating-lobe artifact from off-axis energy", "Acoustic enhancement", "Refraction of the main beam"],
    ans: 1,
    exp: "Off-axis lobes striking a strong reflector are displayed as if they came from the main beam — classic faint 'cavity fog' that a second window dispels.",
    ww: ["Real masses persist across windows.", "", "Enhancement brightens distal tissue, not cavities.", "Refraction shifts real structures; it doesn't invent faint ones."],
    pearl: "Ghosts can't survive a second window." },
  e17: { d: "E", topic: "Aliasing / Nyquist", diff: 2,
    stem: "PW Doppler aliases when the Doppler shift exceeds…",
    ch: ["The transmit frequency", "Half the pulse repetition frequency (Nyquist limit)", "The wall filter setting", "The frame rate"],
    ans: 1,
    exp: "Sampling theory: a sampled signal can only represent shifts up to PRF ÷ 2. Beyond that, the waveform wraps around the baseline.",
    ww: ["Transmit frequency sets the shift's size, not the ceiling.", "", "Wall filters remove LOW frequencies.", "Frame rate is 2D temporal resolution."],
    pearl: "Nyquist = PRF ÷ 2. The wall every PW jet eventually hits." },
  e18: { d: "E", topic: "Fixing aliasing", diff: 2,
    stem: "Which change does NOT help resolve PW aliasing?",
    ch: ["Shifting the baseline", "Increasing the velocity scale (PRF)", "Switching to a higher transmit frequency", "Moving to a shallower sample volume"],
    ans: 2,
    exp: "Higher transmit frequency INCREASES the Doppler shift, making aliasing worse. Every other option raises the effective Nyquist ceiling.",
    ww: ["Baseline shift reallocates the display range — first-line fix.", "Raising scale raises PRF and the Nyquist limit.", "", "Shallower gates allow higher PRF."],
    pearl: "Lower frequency probes measure faster jets before aliasing." },
  e19: { d: "E", topic: "CW vs PW", diff: 1,
    stem: "The fundamental trade-off of continuous-wave Doppler is…",
    ch: ["It aliases at high velocity", "It cannot resolve WHERE along the beam the velocity occurs", "It cannot measure high velocities", "It requires a stand-alone probe only"],
    ans: 1,
    exp: "CW transmits and receives constantly — no Nyquist limit, but every velocity along the entire beam blends together: range ambiguity.",
    ww: ["CW never aliases — that's PW's curse.", "", "High velocities are exactly CW's strength.", "CW is available on imaging transducers too."],
    pearl: "PW knows WHERE. CW knows HOW FAST." },

  // ---------- DOMAIN B — Echo View Gallery (19) ----------
  b1: { d: "B", topic: "PLAX anatomy", diff: 1,
    stem: "Which structures are displayed in a standard parasternal long-axis view?",
    ch: ["LA, LV, MV, AV, LVOT, RVOT", "RA, RV, TV, pulmonic valve", "All four chambers simultaneously", "Aortic arch and descending aorta"],
    ans: 0,
    exp: "PLAX is the left-heart establishing shot: LA, LV, mitral and aortic valves, LVOT, with the RVOT riding anteriorly. The RA is absent.",
    ww: ["", "That's the RV inflow / PSAX territory.", "Four chambers at once is the apical 4-chamber.", "The arch belongs to the suprasternal window."],
    pearl: "" },
  b2: { d: "B", topic: "PLAX technique", diff: 1,
    stem: "Correct probe placement for PLAX is…",
    ch: ["Left sternal border, 3rd–4th ICS, marker toward the right shoulder", "Apex, marker toward the left hip", "Subxiphoid, marker to the patient's left", "Right sternal border, marker to the ceiling"],
    ans: 0,
    exp: "Left sternal border at the 3rd–4th intercostal space with the index marker aimed at the right shoulder (~10 o'clock).",
    ww: ["", "That's an apical setup, not parasternal.", "That's the subcostal window.", "Right parasternal is a supplemental window, and this marker is wrong."],
    pearl: "" },
  b3: { d: "B", topic: "PSAX — AV level", diff: 1,
    stem: "In PSAX at the aortic valve level, a normal AV appears as…",
    ch: ["A fish-mouth opening", "A tri-leaflet 'Mercedes-Benz' configuration", "Two parallel echogenic lines", "A crescent against the septum"],
    ans: 1,
    exp: "Three coapting cusps form the classic Y — surrounded by RA, tricuspid valve, RV, and pulmonary artery around the 'clock face.'",
    ww: ["Fish-mouth is the MITRAL valve at PSAX mitral level.", "", "Parallel lines describe M-mode of a valve, not this face-on view.", "A crescent suggests RV shape, not the AV."],
    pearl: "A bicuspid AV betrays itself here — football-shaped systolic opening." },
  b4: { d: "B", topic: "PSAX — papillary level", diff: 2,
    stem: "The PSAX papillary-muscle level is the standard slice for…",
    ch: ["Measuring the aortic annulus", "Assessing mid-ventricular regional wall motion", "Evaluating the interatrial septum", "Measuring TAPSE"],
    ans: 1,
    exp: "Both papillary muscles anchor the mid-LV segments — this ring is the classic view for regional wall-motion scoring at the mid level.",
    ww: ["The annulus is measured in PLAX zoom.", "", "The IAS is best subcostal.", "TAPSE is an apical/M-mode RV measurement."],
    pearl: "" },
  b5: { d: "B", topic: "A4C technique", diff: 1,
    stem: "A falsely 'short, round' LV in the apical 4-chamber usually means…",
    ch: ["The probe is foreshortening — not at the true apex", "The patient has HCM", "Depth is set too shallow", "The sector is too narrow"],
    ans: 0,
    exp: "Off-apex placement slices the ventricle obliquely: it looks short and rounded, corrupting volumes, EF, and wall-motion reads. Slide to the true apical impulse.",
    ww: ["", "Never diagnose from a foreshortened view.", "Depth changes display size, not shape.", "Sector width crops sides; it doesn't round the apex."],
    pearl: "A foreshortened LV is the most common apical lie — fix the window before you believe it." },
  b6: { d: "B", topic: "A5C", diff: 1,
    stem: "The apical 5-chamber view adds which structure to the A4C?",
    ch: ["The coronary sinus", "The LVOT and aortic valve", "The pulmonary veins", "The descending aorta"],
    ans: 1,
    exp: "A slight anterior tilt opens the LVOT/AV — the 'fifth chamber' — aligning the beam beautifully for LVOT and aortic Doppler.",
    ww: ["The coronary sinus appears with POSTERIOR tilt.", "", "Pulmonary veins are seen in A4C already.", "The descending aorta is a PLAX/A2C bystander."],
    pearl: "" },
  b7: { d: "B", topic: "A2C", diff: 2,
    stem: "Which LV walls are displayed in the apical 2-chamber view?",
    ch: ["Anterior and inferior", "Septal and lateral", "Anteroseptal and inferolateral", "Only the apex"],
    ans: 0,
    exp: "Rotating ~60° counterclockwise from A4C drops the right heart and shows the anterior wall (right of screen) and inferior wall.",
    ww: ["", "Septal + lateral is the A4C pair.", "Anteroseptum + inferolateral is A3C.", "All apical views include more than the apex."],
    pearl: "Wall pairs: A4C septal/lateral · A2C anterior/inferior · A3C anteroseptum/inferolateral." },
  b8: { d: "B", topic: "A3C", diff: 2,
    stem: "The apical 3-chamber (apical long-axis) view is especially useful for…",
    ch: ["Interatrial septum dropout checks", "A second spectral-Doppler window on the LVOT/AV", "Measuring the tricuspid annulus", "Imaging the aortic arch"],
    ans: 1,
    exp: "A3C lines the beam up with the LVOT much like A5C — a vital cross-check for aortic stenosis velocities — while showing anteroseptum and inferolateral walls.",
    ww: ["Septal dropout checks belong to subcostal.", "", "The tricuspid annulus is an A4C/RV-focused job.", "The arch is suprasternal."],
    pearl: "For AS, interrogate multiple windows — the highest clean velocity wins." },
  b9: { d: "B", topic: "Subcostal", diff: 1,
    stem: "The subcostal window is the best alternative in which patient?",
    ch: ["A tall thin marathon runner", "A patient with severe COPD and hyperinflated lungs", "A patient in left lateral decubitus", "Any pediatric patient only"],
    ans: 1,
    exp: "Hyperinflated lungs bury the parasternal and apical windows; the subcostal route slips under them. It's also the effusion and IAS view of choice.",
    ww: ["Thin chests usually image well parasternally.", "", "Subcostal is performed supine with knees bent.", "It's valuable at every age."],
    pearl: "" },
  b10: { d: "B", topic: "IVC / RAP", diff: 2,
    stem: "An IVC measuring 1.6 cm that collapses >50% with a sniff suggests a right atrial pressure of about…",
    ch: ["3 mmHg", "8 mmHg", "15 mmHg", "20 mmHg"],
    ans: 0,
    exp: "Small (≤2.1 cm) + collapsible (>50%) = normal RAP ≈ 3 mmHg (0–5). Dilated and non-collapsing earns 15 mmHg.",
    ww: ["", "8 is the intermediate value when only one criterion is met.", "15 needs a dilated, non-collapsing IVC.", "20 exceeds even the standard high estimate."],
    pearl: "RAP feeds straight into RVSP: RVSP = 4(TR Vmax)² + RAP." },
  b11: { d: "B", topic: "Suprasternal", diff: 1,
    stem: "The suprasternal notch window primarily evaluates…",
    ch: ["The aortic arch and descending aorta", "The interventricular septum", "The mitral valve leaflets", "The coronary arteries"],
    ans: 0,
    exp: "From above the sternum the beam rides the arch — coarctation, dissection flaps, arch flow, and PDA territory.",
    ww: ["", "The IVS belongs to parasternal and apical views.", "Mitral detail lives parasternally and apically.", "Coronaries are not standard TTE targets."],
    pearl: "" },
  b12: { d: "B", topic: "M-mode", diff: 1,
    stem: "M-mode's greatest strength over 2D imaging is…",
    ch: ["Wider field of view", "Superior temporal resolution for timing motion", "Better lateral resolution", "Color-coded flow information"],
    ans: 1,
    exp: "One scan line sampled thousands of times per second captures fine, fast motion — SAM, valve fluttering, mid-systolic notching.",
    ww: ["M-mode is a single line — the narrowest view possible.", "", "Lateral resolution isn't the point of one line.", "Color belongs to Doppler."],
    pearl: "" },
  b13: { d: "B", topic: "Color Doppler", diff: 2,
    stem: "Because color Doppler is pulsed-wave based, it…",
    ch: ["Can alias, with the limit shown on the color bar", "Never aliases", "Measures peak velocities better than CW", "Is angle-independent"],
    ans: 0,
    exp: "Color maps mean velocities from PW packets — so it inherits the Nyquist limit (the number atop the color bar) and angle dependence.",
    ww: ["", "Mosaic patterns ARE color aliasing.", "CW owns peak velocities.", "All Doppler is angle-dependent."],
    pearl: "For regurgitation assessment, set the color Nyquist ~50–70 cm/s." },
  b14: { d: "B", topic: "PW vs CW use", diff: 1,
    stem: "To measure the LVOT velocity specifically AT the LVOT, you should use…",
    ch: ["CW through the whole outflow tract", "PW with the sample volume placed in the LVOT", "Color Doppler alone", "Tissue Doppler at the annulus"],
    ans: 1,
    exp: "PW interrogates one location — sample volume ~0.5 cm proximal to the aortic valve for the LVOT VTI used in continuity and stroke-volume math.",
    ww: ["CW blends every velocity along the line, including the jet.", "", "Color maps flow but yields no clean spectral trace.", "TDI measures myocardium, not blood."],
    pearl: "Continuity needs both: PW for the LVOT, CW for the jet." },
  b15: { d: "B", topic: "Tissue Doppler", diff: 2,
    stem: "Tissue Doppler imaging differs from standard Doppler because it records…",
    ch: ["High-velocity, low-amplitude blood signals", "Low-velocity, high-amplitude myocardial signals", "Only continuous-wave data", "Electrical activity of the myocardium"],
    ans: 1,
    exp: "Filters invert: keep the strong, slow myocardial motion, discard fast blood. e′ at the septal or lateral mitral annulus anchors diastolic assessment.",
    ww: ["That's blood-pool Doppler.", "", "TDI is pulsed at the annulus.", "Electricity is the ECG's job."],
    pearl: "Septal e′ < 7 cm/s flags impaired relaxation." },
  b16: { d: "B", topic: "Agitated saline", diff: 2,
    stem: "After an agitated saline injection, bubbles appear in the left atrium within 3 beats. This indicates…",
    ch: ["A normal study", "An intracardiac shunt such as a PFO or ASD", "A pulmonary arteriovenous malformation", "Severe tricuspid regurgitation"],
    ans: 1,
    exp: "Saline bubbles can't cross healthy lungs. Early left-heart arrival (≤3–6 beats) means an atrial-level shortcut; late arrival suggests a pulmonary AVM.",
    ww: ["Normal studies keep bubbles right-sided.", "", "AVM transit is delayed, not early.", "TR splashes bubbles back into the RA, not the LA."],
    pearl: "A Valsalva release transiently raises right-atrial pressure — the classic PFO unmasking move." },
  b17: { d: "B", topic: "LV contrast", diff: 2,
    stem: "Transpulmonary contrast (an ultrasound enhancing agent) is indicated when…",
    ch: ["Any study runs long", "Two or more contiguous LV segments cannot be visualized", "The patient has a known PFO", "Color Doppler is unavailable"],
    ans: 1,
    exp: "UEAs cross the lungs and opacify the LV — rescuing EF accuracy, wall-motion reads, and apical thrombus detection when ≥2 contiguous segments are unreadable.",
    ww: ["Study length is not an indication.", "", "PFO hunting uses agitated saline, not UEA.", "Contrast doesn't replace color Doppler."],
    pearl: "Saline = Shunts. Contrast = Chambers." },
  b18: { d: "B", topic: "Exercise stress echo", diff: 2,
    stem: "In treadmill stress echo, post-exercise images must be captured…",
    ch: ["Within about 60–90 seconds, before heart rate recovers", "After a 5-minute cooldown for stability", "Only if symptoms occur", "The next day for comparison"],
    ans: 0,
    exp: "Ischemic wall-motion abnormalities fade as heart rate falls — the diagnostic window is the first minute or so after peak exercise.",
    ww: ["", "A cooldown erases the very findings you need.", "Imaging is required regardless of symptoms.", "Next-day imaging is meaningless for ischemia."],
    pearl: "New or worsening wall motion with stress = ischemia; fixed abnormality = prior infarct." },
  b19: { d: "B", topic: "Dobutamine stress", diff: 3,
    stem: "During dobutamine stress echo, a segment improves at low dose then worsens at peak. This biphasic response indicates…",
    ch: ["Normal myocardium", "Artifact from tachycardia", "Viable but ischemic myocardium", "Completed transmural infarct"],
    ans: 2,
    exp: "Low-dose improvement proves contractile reserve (viability); peak-dose deterioration proves demand ischemia — the classic biphasic signature guiding revascularization.",
    ww: ["Normal segments augment progressively throughout.", "Rate artifacts don't follow this staged pattern.", "", "Scar neither improves nor worsens — it stays akinetic."],
    pearl: "Atropine is added when heart-rate targets aren't met." },
};

// ============================ MEASURE MATCH ============================
export const MM_ROUNDS = [
  { m: "Aortic valve peak velocity (Vmax)",
    stages: [
      { k: "WINDOW", prompt: "Best window to capture the jet?", opts: ["Apical 5-chamber", "PSAX papillary level", "Subcostal IVC", "Suprasternal notch"], ans: 0, why: "A5C (or apical long-axis) aligns the beam with aortic flow." },
      { k: "MODALITY", prompt: "Which Doppler mode?", opts: ["PW at the leaflet tips", "CW through the valve", "Tissue Doppler", "Color M-mode"], ans: 1, why: "AS jets exceed the Nyquist limit — CW captures peak velocity without aliasing." },
      { k: "MEANING", prompt: "This measurement feeds…", opts: ["Aortic stenosis severity", "RA pressure estimate", "Diastolic grading", "LA volume index"], ans: 0, why: "Vmax ≥ 4 m/s is a hallmark of severe aortic stenosis." },
    ] },
  { m: "LVOT VTI (velocity-time integral)",
    stages: [
      { k: "WINDOW", prompt: "Where do you sample it?", opts: ["Apical 5-chamber", "PLAX", "Subcostal 4C", "PSAX AV level"], ans: 0, why: "A5C lets you park the PW gate in the LVOT parallel to flow." },
      { k: "MODALITY", prompt: "Which Doppler mode?", opts: ["CW through the AV", "PW ~0.5 cm proximal to the AV", "Color Doppler", "M-mode"], ans: 1, why: "PW gives the site-specific LVOT envelope; CW would contaminate with the jet." },
      { k: "MEANING", prompt: "This measurement feeds…", opts: ["Stroke volume & the continuity equation", "Pericardial effusion sizing", "Wall motion scoring", "IVC collapsibility"], ans: 0, why: "SV = CSA(LVOT) × VTI(LVOT); continuity solves the valve area." },
    ] },
  { m: "Mitral E and A velocities",
    stages: [
      { k: "WINDOW", prompt: "Best window?", opts: ["Apical 4-chamber", "PLAX", "Suprasternal", "PSAX AV"], ans: 0, why: "A4C aligns with mitral inflow." },
      { k: "MODALITY", prompt: "Which mode & placement?", opts: ["PW at the mitral leaflet tips", "CW across the annulus", "TDI in the LA", "Color M-mode only"], ans: 0, why: "PW at the leaflet tips records the classic E and A filling waves." },
      { k: "MEANING", prompt: "This measurement feeds…", opts: ["Diastolic filling pattern (E/A)", "Aortic regurgitation severity", "RVSP", "LV mass"], ans: 0, why: "E/A ratio is the first brushstroke of diastolic assessment." },
    ] },
  { m: "Septal e′ (annular velocity)",
    stages: [
      { k: "WINDOW", prompt: "Best window?", opts: ["Apical 4-chamber", "PSAX papillary", "PLAX zoom", "Subcostal SAX"], ans: 0, why: "A4C shows the septal and lateral mitral annulus for TDI." },
      { k: "MODALITY", prompt: "Which mode?", opts: ["CW Doppler", "Tissue Doppler at the septal annulus", "PW in the LVOT", "3D color"], ans: 1, why: "TDI keeps the slow, strong myocardial signal — that's e′." },
      { k: "MEANING", prompt: "Combined with mitral E, e′ gives…", opts: ["E/e′ — an LV filling-pressure estimate", "Valve area", "Cardiac output", "Aortic compliance"], ans: 0, why: "E/e′ > 14 suggests elevated filling pressure." },
    ] },
  { m: "Tricuspid regurgitation Vmax",
    stages: [
      { k: "WINDOW", prompt: "Where do you hunt the strongest jet?", opts: ["A4C / RV-focused (and others!)", "Suprasternal only", "PLAX only", "Subcostal IVC"], ans: 0, why: "Sweep every window — the best-aligned TR envelope wins." },
      { k: "MODALITY", prompt: "Which mode?", opts: ["PW in the RA", "CW through the TR jet", "TDI at the RV base", "Color only"], ans: 1, why: "TR jets run 2–4+ m/s — CW territory." },
      { k: "MEANING", prompt: "4 × (TR Vmax)² + RAP estimates…", opts: ["RVSP / pulmonary artery systolic pressure", "LV end-diastolic pressure", "Aortic mean gradient", "LA pressure directly"], ans: 0, why: "The modified Bernoulli equation converts the jet into RV systolic pressure." },
    ] },
  { m: "IVC diameter & sniff collapse",
    stages: [
      { k: "WINDOW", prompt: "Best window?", opts: ["Subcostal long-axis IVC", "A2C", "PSAX mitral", "Right parasternal"], ans: 0, why: "The subcostal window lays the IVC out for measurement just caudal to the RA." },
      { k: "MODALITY", prompt: "How is it assessed?", opts: ["2D ± M-mode with a sniff test", "CW Doppler", "Agitated saline", "Strain imaging"], ans: 0, why: "Measure diameter and watch inspiratory collapse — M-mode helps timing." },
      { k: "MEANING", prompt: "This estimates…", opts: ["Right atrial pressure", "LV filling pressure", "Aortic valve area", "Pericardial pressure"], ans: 0, why: "Size + collapsibility bins RAP at 3, 8, or 15 mmHg." },
    ] },
];

// ============================ DOPPLER DUEL ============================
export const DUEL_ROUNDS = [
  { scene: "A jet screams past at 5.2 m/s. The rogue console dares you to trace its peak.",
    prompt: "Which weapon do you draw?",
    opts: ["PW — precision sampling", "CW — the unlimited blade", "Color Doppler alone", "M-mode"],
    ans: 1, why: "Velocities this high smash through the PW Nyquist ceiling. CW never aliases.", tip: "PW knows WHERE. CW knows HOW FAST." },
  { scene: "Your PW trace wraps around the baseline — the envelope's head appears below zero.",
    prompt: "The artifact and its first fix?",
    opts: ["Mirror image — lower the gain", "Aliasing — shift the baseline / raise the scale", "Range ambiguity — go deeper", "Wall clutter — raise the filter"],
    ans: 1, why: "Classic aliasing wraparound. Baseline shift and a higher velocity scale (PRF) reclaim the range.", tip: "Still wrapping after every trick? Surrender to CW." },
  { scene: "The console demands: WHERE exactly does flow accelerate in the LVOT?",
    prompt: "Only one mode can answer 'where.'",
    opts: ["CW Doppler", "PW Doppler — range-specific sampling", "Continuous color sweep", "Higher 2D gain"],
    ans: 1, why: "PW's sample volume interrogates one depth — that's range resolution, its whole superpower.", tip: "" },
  { scene: "Three probe lines glow: 0°, 45°, and 70° to the jet.",
    prompt: "Which alignment tells the truth?",
    opts: ["70° — style points", "45° — a fair compromise", "0° — parallel to flow", "Angle never matters"],
    ans: 2, why: "Doppler shift scales with cos(θ). At 0° you capture it all; beyond 60° the lie exceeds 50%.", tip: "cos 60° = 0.5 — half the velocity vanishes." },
  { scene: "The console flashes: PRF = 8,000 Hz. Which Doppler shift ALIASES?",
    prompt: "Recall the Nyquist law…",
    opts: ["2,000 Hz", "3,900 Hz", "4,000 Hz exactly", "5,000 Hz"],
    ans: 3, why: "Nyquist = PRF ÷ 2 = 4,000 Hz. Only shifts ABOVE it wrap — 5,000 Hz aliases.", tip: "At exactly Nyquist the trace teeters; beyond it, it wraps." },
  { scene: "Color box on a normal LA: the whole chamber shimmers into mosaic. Scale reads 20 cm/s.",
    prompt: "Your move?",
    opts: ["Report severe regurgitation", "Raise the color scale toward 50–70 cm/s", "Widen the color box", "Add more 2D gain"],
    ans: 1, why: "A low color Nyquist makes normal flow alias into mosaic. Standard regurg assessment sits ~50–70 cm/s.", tip: "Check the color bar before you believe any mosaic." },
];

// ============================ BOSSES ============================
export const BOSSES = [
  { id: "angels", name: "The Weeping Angels", sub: "Timed Trial · fast recall", unlockLevel: 3,
    mech: "Answer before the clock dies. Wrong or slow — the Angels advance. Four advances and they reach you.",
    time: 15, count: 10, strikes: 4, xp: 60, badge: "dont_blink", artifact: "chrono", mvp: true,
    intro: "They only move when you hesitate, Lizzie. Knowledge is the blink-proof stare. Ten questions. Don't look away." },
  { id: "autons", name: "The Auton Anatomy Ambush", sub: "Anatomy & views", unlockLevel: 5, mvp: false, act: "Act II" },
  { id: "sontaran", name: "Sontaran Pressure War", sub: "Gradients & hemodynamics", unlockLevel: 12, mvp: false, act: "Act II" },
  { id: "cybermen", name: "Cyberman Valve Conversion", sub: "Valvular severity logic", unlockLevel: 20, mvp: false, act: "Act III" },
  { id: "vashta", name: "Vashta Nerada Artifact Hunt", sub: "Artifacts & optimization", unlockLevel: 16, mvp: false, act: "Act II" },
  { id: "silence", name: "The Silence Memory Core", sub: "Weak-area recall", unlockLevel: 24, mvp: false, act: "Act III" },
  { id: "dalek", name: "Dalek Final Scan", sub: "Comprehensive mixed exam", unlockLevel: 35, mvp: false, act: "Act III" },
  { id: "master", name: "The Master's False Report", sub: "Find every error. Defend the read.", unlockLevel: 45, mvp: false, act: "Finale" },
];

export const ONBOARDING = [
  { sp: "???", t: "You hear it before you see it — a wheezing, groaning engine, like the universe clearing its throat. A blue box fades into your study room." },
  { sp: "The Fourteenth Doctor", t: "Lizzie! Brilliant timing. The doors only open for people who are about to become extraordinary — and you, future Registered Cardiac Sonographer, qualify twice." },
  { sp: "The Fourteenth Doctor", t: "Welcome to the TARDIS. Time And Relative Dimension In Space — and, since a small accident with the learning core, a fully operational echocardiography academy. It runs my memories backwards. You'll meet… earlier versions of me. Be nice to the eyebrows." },
  { sp: "The Fourteenth Doctor", t: "Here's the secret nobody tells you: every echo image is a fixed point in time. Learn where to stand, where to aim, what the wave is doing — and no exam question in this universe can ambush you." },
  { sp: "The Fourteenth Doctor", t: "One more thing. When is your registry exam? Give the TARDIS the date and she'll pace your whole training to land on it. She's very good at landing. Mostly." },
];

export const DISCLAIMER = "Fan-inspired study project. Not affiliated with, or endorsed by, the BBC, Doctor Who, CCI, or Pearson VUE. All study content is original and for practice only — no outcome on any exam is guaranteed.";
